### ISSUE TITLE
BedrijventerreinBebouwing

### ISSUE THREAD

**Issue by IdrisPeiren** [Informatievlaanderen/bron-bedrijventerreinen#1]
Bebouwing is enkel van toepassing voor een bedrijventerreinperceel. Moet de domeinnaam dan niet aangepast worden naar BedrijventerreinperceelBebouwing?

cfr. BedrijventerreinperceelFunctie

**Comment by bertvannuffelen** [comment]
zolang de betekenis van de term eenduidig is in de context van een klasse is dat niet nodig. Disambiguatie wordt enkel toegepast indien noodzakelijk. Zo blijven de termen compact.
