### ISSUE TITLE
Foute link Bebouwing

### ISSUE THREAD

**Issue by AnneliesSmeets** [Informatievlaanderen/bron-bedrijventerreinen#24]
De link van bebouwing in Bedrijventerreinperceel verwijst naar een verkeerde pagina (https://data.vlaanderen.be/doc/conceptscheme/BedrijventerreinBebouwing). 

Dit moet gewijzigd worden naar: https://data.vlaanderen.be/doc/conceptscheme/BedrijventerreinperceelBebouwing

**Comment by bertvannuffelen** [comment]
Oplossing in https://bedrijventerreinen.dev-vlaanderen.be/doc/implementatiemodel/bedrijventerrein/ontwerpdocument/2022-04-05#Bedrijventerreinperceelaanbieding
