### ISSUE TITLE
Foute link RuimtelijkeEenheidtype

### ISSUE THREAD

**Issue by AnneliesSmeets** [Informatievlaanderen/bron-bedrijventerreinen#25]
Link RuimtelijkeEenheidType bij Bedrijventerreinperceel is niet juist.

Juiste link: https://data.vlaanderen.be/doc/conceptscheme/BedrijventerreinperceelRuimtelijkeEenheidtype

**Comment by bertvannuffelen** [comment]
Dit lijkt me een probleem van de tooling te zijn. Staat niet in het UML diagramma, maar wordt wel aangemaakt.

**Comment by AnneliesSmeets** [comment]
De link verwijst nog steeds naar https://data.vlaanderen.be/doc/conceptscheme/RuimtelijkeEenheidtype

**Comment by AnneliesSmeets** [comment]
Hier is het wel opgelost: https://bedrijventerreinen.dev-vlaanderen.be/doc/implementatiemodel/bedrijventerrein/ontwerpdocument/2022-06-17
