### ISSUE TITLE
Link RuimtelijkeEenheidType Bedrijventerrein + BeheerdeBedrijvenzone

### ISSUE THREAD

**Issue by AnneliesSmeets** [Informatievlaanderen/bron-bedrijventerreinen#26]
Link RuimtelijkeEenheidType Bedrijventerrein + BeheerdeBedrijvenzone is niet juist. Het is niet duidelijk welke de juiste link dan wel is.

**Comment by bertvannuffelen** [comment]
Dit lijkt een probleem van de tooling te zijn. Staat niet in UML diagramma, maar wordt wel aangemaakt.

**Comment by bertvannuffelen** [comment]
opgelost in https://bedrijventerreinen.dev-vlaanderen.be/doc/implementatiemodel/bedrijventerrein/ontwerpdocument/2022-06-17

**Comment by AnneliesSmeets** [comment]
De link in kolom 'Codelijst' is verdwenen
