### ISSUE TITLE
Link toevoegen voor Bedrijventerreinperceel Functie

### ISSUE THREAD

**Issue by AnneliesSmeets** [Informatievlaanderen/bron-bedrijventerreinen#27]
Er is nog geen link voor de Functie van Bedrijventerreinperceel. 

Dit zou de link moeten zijn: https://data.vlaanderen.be/doc/conceptscheme/BedrijventerreinperceelFunctie

**Comment by bertvannuffelen** [comment]
Opgelost in https://bedrijventerreinen.dev-vlaanderen.be/doc/implementatiemodel/bedrijventerrein/ontwerpdocument/2022-04-05#Functiewaarde

**Comment by AnneliesSmeets** [comment]
Ok die link staat dus bij type onder Functiewaarde.
