### ISSUE TITLE
Beschrijving Functie Bedrijventerreinperceel

### ISSUE THREAD

**Issue by AnneliesSmeets** [Informatievlaanderen/bron-bedrijventerreinen#28]
We werken niet met een percentage voor functie. 

De beschrijving mag gewijzigd worden naar: Deze eigenschap geeft welke functie men kan terugvinden op het Bedrijventerreinperceel.

**Comment by bertvannuffelen** [comment]
https://bedrijventerreinen.dev-vlaanderen.be/doc/implementatiemodel/bedrijventerrein/ontwerpdocument/2022-06-17#Bedrijventerreinperceel%3Afunctie
