### ISSUE TITLE
Foute link Status Ontwikkeling

### ISSUE THREAD

**Issue by AnneliesSmeets** [Informatievlaanderen/bron-bedrijventerreinen#29]
De link van StatusOntwikkeling (OntwikkelbareBedrijvenzone) is niet juist. 

Dit is de juiste link: https://data.vlaanderen.be/doc/conceptscheme/OntwikkelbareBedrijvenzoneOntwikkelingsstatus

**Comment by bertvannuffelen** [comment]
Zou opgelost moeten zijn in https://bedrijventerreinen.dev-vlaanderen.be/doc/implementatiemodel/bedrijventerrein/ontwerpdocument/2022-04-05#Bedrijventerreinperceelaanbieding

**Comment by bertvannuffelen** [comment]
verbeterd in https://bedrijventerreinen.dev-vlaanderen.be/doc/implementatiemodel/bedrijventerrein/ontwerpdocument/2022-06-17#Ontwikkelbare%20Bedrijvenzone%3Astatus%20ontwikkeling
