### ISSUE TITLE
BedrijventerreinperceelAanbieding

### ISSUE THREAD

**Issue by AnneliesSmeets** [Informatievlaanderen/bron-bedrijventerreinen#31]
BedrijventerreinperceelAanbieding is een aparte tabel is ons model. Dit wordt zo nog niet weergegeven op de pagina van het implementatiemodel. HomepageAanbieding en Aanbieder staat bijvoorbeeld nog steeds bij Bedrijventerreinperceel i.p.v. bij BedrijventerreinperceelAanbieding.

**Comment by bertvannuffelen** [comment]
Ook hier beschikbaar https://bedrijventerreinen.dev-vlaanderen.be/doc/implementatiemodel/bedrijventerrein/ontwerpdocument/2022-06-17#Bedrijventerreinperceelaanbieding
