### ISSUE TITLE
Figuur Schema implementatiemodel

### ISSUE THREAD

**Issue by AnneliesSmeets** [Informatievlaanderen/bron-bedrijventerreinen#32]
De figuur zou nog vernieuwd moeten worden. Bedrijventerreinperceel zit er nog niet in, eventueel de aparte blok Functiewaarde verwijderen (zie issue https://github.com/Informatievlaanderen/bron-bedrijventerreinen/issues/30).

https://bedrijventerrein.vlaanderen.be/doc/implementatiemodel/bedrijventerrein/erkendestandaard/2021-04-01/html/overview.jpg

**Comment by bertvannuffelen** [comment]
nieuwe model beschikbaar op https://bedrijventerreinen.dev-vlaanderen.be/doc/implementatiemodel/bedrijventerrein/ontwerpdocument/2022-04-05#Bedrijventerreinperceelaanbieding
