### ISSUE TITLE
Wijziging gebruik Bebouwing

### ISSUE THREAD

**Issue by AnneliesSmeets** [Informatievlaanderen/bron-bedrijventerreinen#33]
Infrastructuur komt niet voor bij Bebouwing.
Gebruik van Bebouwing (Bedrijventerreinperceel) mag dus gewijzigd worden naar 'Mogelijke waarden kunnen zijn: bebouwd, onbebouwd'.

**Comment by AnneliesSmeets** [comment]
Er is nog een typfoutje: de 'd' van 'onbebouwd' ontbreekt.

**Comment by bertvannuffelen** [comment]
Zie https://bedrijventerreinen.dev-vlaanderen.be/doc/implementatiemodel/bedrijventerrein/ontwerpdocument/2022-06-17#Bedrijventerreinperceel%3Abebouwing
