### ISSUE TITLE
Nieuw attribuut: 'BronAanbieding'

### ISSUE THREAD

**Issue by AnneliesSmeets** [Informatievlaanderen/bron-bedrijventerreinen#34]
Het attribuut 'BronAanbieding' van de tabel 'BedrijventerreinperceelAanbieding' zou toegevoegd moeten worden aan het implementatiemodel. Het attribuut is momenteel reeds zichtbaar op Geopunt.
BedrijventerreinperceelAanbieding bestaat nog niet, zie issue https://github.com/Informatievlaanderen/bron-bedrijventerreinen/issues/31.

Eigenschap: BronAanbieding
Verwacht Type: TaalString 
Kardinaliteit: 1
Beschrijving: Deze eigenschap geeft aan van welke bron de aanbieding afkomstig is. 
Gebruik: Mogelijke waarden kunnen zijn: bizLocator, Businesscenter, VLAIO of de naam van een partner die gegevens aanlevert via Decentraal Medebeheer. 
Codelijst: /

Verwacht Type en Kardinaliteit ben ik niet zeker van.

**Comment by bertvannuffelen** [comment]
ivm de identificator: wil je kunnen verwijzen naar deze aanbieding in tijd en ruimte (dus persistent houden?) Of is dit meer een stukje kennis dat "ge-embed" zit in het perceel. Volgens mij kan een aanbieding niet bestaan zonder  het bestaan van een perceel. We kunnen in de publicatie een lokale id maken die coherent is, maar die niet persistent is.

**Comment by bertvannuffelen** [comment]
voorstel in https://bedrijventerreinen.dev-vlaanderen.be/doc/implementatiemodel/bedrijventerrein/ontwerpdocument/2022-04-05#Bedrijventerreinperceelaanbieding

**Comment by bertvannuffelen** [comment]
voorstel in https://bedrijventerreinen.dev-vlaanderen.be/doc/implementatiemodel/bedrijventerrein/ontwerpdocument/2022-06-17#Bedrijventerreinperceelaanbieding
