### ISSUE TITLE
Homepage BeheerdeBedrijvenzone toevoegen

### ISSUE THREAD

**Issue by AnneliesSmeets** [Informatievlaanderen/bron-bedrijventerreinen#37]
Het veld 'Homepage' ontbreekt bij de BeheerdeBedrijvenzone. 

Eigenschap: Homepage
Verwacht Type: String
Kardinaliteit: 1
Beschrijving: Link naar de webpagina van de beheerde bedrijvenzone
Gebruik: /
Codelijst: /

**Comment by bertvannuffelen** [comment]
toegevoegd met card 0..1
Zie https://bedrijventerreinen.dev-vlaanderen.be/doc/implementatiemodel/bedrijventerrein/ontwerpdocument/2022-06-17#Beheerde%20Bedrijvenzone%3Ahomepage
