### ISSUE TITLE
Beschrijving StatusOntwikkeling

### ISSUE THREAD

**Issue by AnneliesSmeets** [Informatievlaanderen/bron-bedrijventerreinen#38]
Typfout in de beschrijving van 'StatusOntwikkeling' van de ontwikkelbare bedrijvenzone. Aanpassen naar: Geeft de status aan van de Ontwikkelbare Bedrijvenzone.

**Comment by bertvannuffelen** [comment]
Zie https://bedrijventerreinen.dev-vlaanderen.be/doc/implementatiemodel/bedrijventerrein/ontwerpdocument/2022-06-17#Ontwikkelbare%20Bedrijvenzone%3Astatus%20ontwikkeling
