### ISSUE TITLE
Beschrijving Voorziene Uitgifte

### ISSUE THREAD

**Issue by AnneliesSmeets** [Informatievlaanderen/bron-bedrijventerreinen#39]
De beschrijving van Voorziene Uitgifte van de ontwikkelbare Bedrijvenzone mag gewijzigd worden naar: "Het tijdstip waarop de eerste uitgifte binnen de ontwikkelbare bedrijvenzone is voorzien."

**Comment by bertvannuffelen** [comment]
Zie https://bedrijventerreinen.dev-vlaanderen.be/doc/implementatiemodel/bedrijventerrein/ontwerpdocument/2022-06-17#Ontwikkelbare%20Bedrijvenzone%3Avoorziene%20uitgifte
