### ISSUE TITLE
relatie Bedrijventerreinperceel en beheerde bedrijvenzone

### ISSUE THREAD

**Issue by AnneliesSmeets** [Informatievlaanderen/bron-bedrijventerreinen#40]
Er is geen verwijzing naar de Beheerde Bedrijvenzone bij Bedrijventerreinperceel. 
Bij de beheerde Bedrijvenzone is er wel een eigenschap: "is gerelateerd aan Bedrijventerreinperceel". Maar dit klopt niet en moet verwijderd worden. Het moet andersom zijn en dus bij Bedrijventerreinperceel moet toegevoegd worden: "is gerelateerd aan Beheerde Bedrijvenzone". De beschrijving mag gewoon overgenomen worden: "Beheerde bedrijvenzone waarmee het bedrijventerreinperceel kan geassocieerd worden."

![ID_BeheerdeBedrijvenzone](https://user-images.githubusercontent.com/83573038/162265765-92aaf706-e485-4329-a13e-38e3ac9d9b25.PNG)

**Comment by bertvannuffelen** [comment]
Opgelost in https://bedrijventerreinen.dev-vlaanderen.be/doc/implementatiemodel/bedrijventerrein/ontwerpdocument/2022-06-17
