### ISSUE TITLE
Beschrijving Beperking

### ISSUE THREAD

**Issue by AnneliesSmeets** [Informatievlaanderen/bron-bedrijventerreinen#41]
De beschrijving van Beperking (Bedrijventerreinperceel) mag aangepast worden naar: "Deze eigenschap geeft aan welke mogelijke beperking(en) een bepaald bedrijventerreinperceel momenteel ondervindt. "

**Comment by bertvannuffelen** [comment]
Zie https://bedrijventerreinen.dev-vlaanderen.be/doc/implementatiemodel/bedrijventerrein/ontwerpdocument/2022-06-17#Bedrijventerreinperceel%3Abeperking
